title: Felix Geisendörfer
url: http://felixge.de
author:
  name: Felix Geisendörfer
  uri: http://felixge.de/
timezone: UTC
markdown: redcarpet
pygments: true
exclude:
  - NEXT.md
gems:
  - jekyll-less
